[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.28"
viaIR = true
evm_version = "cancun"
optimizer = true
optimizer_runs = 20_000

[fmt]
line_length = 100
number_underscore = "thousands"
tab_width = 4
